# Assignment 3

**Please follow the instructions. Do not add new cell! Write your code in designated areas.**

In [ ]:
import datetime
import socket

# Get local time
local_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# Get computer ID or hostname
computer_id = socket.gethostname()

# Print output with local time and computer ID
print('Assignment 1 & 2: Solutions by John') # Please change your name here
print('Local Time:', local_time)
print('Computer ID:', computer_id)

## NumPy

In [3]:
import numpy as np
import pandas as pd


1. Create a 2D numpy array of size 4x5 with random integers between 1 and 10. Find the maximum value of the entire array. 


In [8]:
## Your code here down
random_array = np.random.randint(1, 11, size=(4, 5))

# Print the random array
print("Random Array:")
print(random_array)

# Find the maximum value in the entire array
max_value = np.max(random_array)
mean = np.mean(random_array)
print(mean)

## Your code here up

Random Array:
[[ 5  9  8  6 10]
 [ 4  1  5  1  1]
 [ 5  2  3  3  8]
 [ 4  3  2  4  1]]
4.25


2. Create a 1D numpy array of size 20 with random floats between 0 and 1. Reshape the array into a 4x5 matrix. Compute the mean of each row.

In [9]:
## Your code here down
random_floats = np.random.random(20)

# Reshape the array into a 4x5 matrix
matrix = random_floats.reshape(4, 5)


row_means = np.mean(matrix, axis=1)

print("1D Array:")
print(random_floats)
print("\nReshaped Matrix (4x5):")
print(matrix)
print("\nMean of each row:")
print(row_means)

## Your code here up

1D Array:
[0.48743725 0.62330337 0.85986842 0.62154212 0.17955805 0.20773343
 0.1689941  0.65223123 0.93789135 0.26944637 0.51143896 0.02635551
 0.62513341 0.7724302  0.21128478 0.52941746 0.18541896 0.15944644
 0.86542933 0.68643421]

Reshaped Matrix (4x5):
[[0.48743725 0.62330337 0.85986842 0.62154212 0.17955805]
 [0.20773343 0.1689941  0.65223123 0.93789135 0.26944637]
 [0.51143896 0.02635551 0.62513341 0.7724302  0.21128478]
 [0.52941746 0.18541896 0.15944644 0.86542933 0.68643421]]

Mean of each row:
[0.55434184 0.4472593  0.42932857 0.48522928]


3. Create a 2D numpy array of size 5x5 with random integers between 1 and 100. Compute standard deviation of each column.

In [10]:
## Your code here down
random_integers = np.random.randint(1, 101, size=(5, 5))

# Print the random array
print("Random Array:")
print(random_integers)

# Compute the standard deviation of each column
column_std = np.std(random_integers, axis=0)

# Print the standard deviation of each column
print("\nStandard deviation of each column:")
print(column_std)

## Your code here up

Random Array:
[[ 44  69  70  55  70]
 [ 31  68  26  93   3]
 [ 27  36  10  32  83]
 [ 79  77  46  30  32]
 [ 31 100  92  57  98]]

Standard deviation of each column:
[19.17915535 20.54263858 29.49169375 22.75609808 34.83331738]


4. Create a 1D numpy array of size 15 with random floats between -10 and 10. Replace all negative values with their absolute values.

In [11]:
## Your code here down
random_floats = np.random.uniform(-10, 10, 15)

# Print the original 1D array
print("Original Array:")
print(random_floats)

# Replace negative values with their absolute values
random_floats = np.abs(random_floats)

# Print the array after replacing negative values with their absolute values
print("\nArray after replacing negative values with absolute values:")
print(random_floats)

## Your code here up

Original Array:
[-1.60035091 -8.01418315  2.13830878 -3.43564802  6.54532914 -4.76404908
  4.81309885  7.12375451  2.8764425   4.55594695 -1.79888936  3.76076022
 -6.89027737 -9.25961368 -9.17732061]

Array after replacing negative values with absolute values:
[1.60035091 8.01418315 2.13830878 3.43564802 6.54532914 4.76404908
 4.81309885 7.12375451 2.8764425  4.55594695 1.79888936 3.76076022
 6.89027737 9.25961368 9.17732061]


5. Create a 2D numpy array of size 3x4 with random integers between 1 and 100. Calculate the sum of all elements in the array.

In [12]:
## Your code here down
random_integers = np.random.randint(1, 101, size=(3, 4))

# Print the random array
print("Random Array:")
print(random_integers)

# Calculate the sum of all elements in the array
total_sum = np.sum(random_integers)

# Print the sum of all elements in the array
print("\nSum of all elements in the array:", total_sum)

## Your code here up

Random Array:
[[82 54 47 57]
 [45 14  6  2]
 [53  5 28 40]]

Sum of all elements in the array: 433


7. Create a 2D numpy array of size 4x6 with random floats between 0 and 1. Normalize each column by subtracting the column mean and dividing by the column standard deviation.

In [13]:
## Your code here down
random_floats = np.random.random((4, 6))

# Print the original array
print("Original Array:")
print(random_floats)

# Calculate the mean and standard deviation of each column
column_means = np.mean(random_floats, axis=0)
column_stds = np.std(random_floats, axis=0)

# Normalize each column
normalized_array = (random_floats - column_means) / column_stds

# Print the normalized array
print("\nNormalized Array:")
print(normalized_array)

## Your code here up

Original Array:
[[0.29075112 0.02991325 0.684239   0.21239617 0.93591175 0.35112491]
 [0.55089184 0.67661975 0.2166171  0.36109694 0.70211901 0.70924695]
 [0.54603781 0.81889499 0.07411764 0.4944698  0.80557281 0.70945131]
 [0.88094905 0.51927061 0.06062536 0.14869533 0.02341611 0.42538199]]

Normalized Array:
[[-1.31930473 -1.61833241  1.6807808  -0.68376618  0.90556775 -1.21512185]
 [-0.0776368   0.55634041 -0.16708525  0.42420311  0.24220998  0.98626364]
 [-0.10080539  1.0347678  -0.73018956  1.41796418  0.53574724  0.98751985]
 [ 1.49774691  0.0272242  -0.78350598 -1.15840111 -1.68352496 -0.75866163]]


8. Create a 2D numpy array of size 10x10 with random integers between 1 and 100. Replace all values greater than 50 with 1 and all other values with 0.

In [14]:
## Your code here down

random_integers = np.random.randint(1, 101, size=(10, 10))

# Print the original array
print("Original Array:")
print(random_integers)

# Replace values greater than 50 with 1 and others with 0
binary_array = np.where(random_integers > 50, 1, 0)

# Print the array after replacement
print("\nArray after replacement:")
print(binary_array)
## Your code here up

Original Array:
[[ 72  42  68  48   3  22  60  20  16  67]
 [ 26  92  73  31  59  49  16  38  92  82]
 [ 75  71  10  30  93  91  70  19  39  52]
 [ 20  62  78  16   9  77  47  52  57  72]
 [ 20  28  14  27   9  42   9  56  92   9]
 [ 52   5  75  15  74  12  15  74  40  60]
 [ 12  85  76  70  55  88   7  44  39  82]
 [ 14  85   9  20  66  56  74  66  87  15]
 [ 95  43  61  52  33  66  35  86 100  45]
 [  6  54  97  84  89  26  37  75  68  77]]

Array after replacement:
[[1 0 1 0 0 0 1 0 0 1]
 [0 1 1 0 1 0 0 0 1 1]
 [1 1 0 0 1 1 1 0 0 1]
 [0 1 1 0 0 1 0 1 1 1]
 [0 0 0 0 0 0 0 1 1 0]
 [1 0 1 0 1 0 0 1 0 1]
 [0 1 1 1 1 1 0 0 0 1]
 [0 1 0 0 1 1 1 1 1 0]
 [1 0 1 1 0 1 0 1 1 0]
 [0 1 1 1 1 0 0 1 1 1]]


9. Create a 1D numpy array of size 50 with random floats between 0 and 1. Find the number of elements greater than 0.5.

In [15]:
## Your code here down
random_floats = np.random.random(50)

# Print the original 1D array
print("Original Array:")
print(random_floats)

# Count the number of elements greater than 0.5
count_greater_than_0_5 = np.sum(random_floats > 0.5)

# Print the count
print("\nNumber of elements greater than 0.5:", count_greater_than_0_5)

## Your code here up

Original Array:
[0.27272522 0.42354916 0.65722686 0.32456699 0.12258705 0.28287
 0.83217961 0.62638968 0.3373439  0.72603257 0.78396865 0.03459583
 0.75002812 0.62068739 0.35471286 0.50958288 0.9670402  0.31463942
 0.08148433 0.20477876 0.72218188 0.86750423 0.83870985 0.89436469
 0.75563267 0.01417286 0.73679014 0.65383108 0.34218846 0.89289266
 0.39049032 0.85634616 0.28826999 0.53426914 0.66498648 0.65725415
 0.57260789 0.95158226 0.86027754 0.27648774 0.50382103 0.88065736
 0.60033645 0.30837343 0.19902573 0.57809387 0.13523824 0.32595037
 0.73038415 0.60286291]

Number of elements greater than 0.5: 30


10. Create a 2D numpy array of size 5x5 with random floats between -1 and 1. Find the absolute difference between the maximum and minimum values in each row.

In [16]:
## Your code here down
random_floats = np.random.uniform(-1, 1, size=(5, 5))

# Print the original array
print("Original Array:")
print(random_floats)

# Calculate the absolute difference between the maximum and minimum values in each row
row_abs_diff = np.abs(np.max(random_floats, axis=1) - np.min(random_floats, axis=1))

# Print the absolute difference for each row
print("\nAbsolute difference between max and min values in each row:")
print(row_abs_diff)

## Your code here up

Original Array:
[[-0.28866087  0.88244241  0.38009931  0.14059256 -0.36750329]
 [ 0.53893218  0.41504507 -0.48422702  0.70773134 -0.98538703]
 [ 0.25222488  0.11240666 -0.57228874 -0.75445587 -0.56969491]
 [ 0.59494661  0.79315228 -0.66681069 -0.76370857 -0.70302399]
 [-0.64084266 -0.5820088   0.42143022 -0.43475693 -0.40891102]]

Absolute difference between max and min values in each row:
[1.2499457  1.69311838 1.00668076 1.55686085 1.06227287]


## Pandas

Please refer the dataframe (farm data) we have created in the training. Please copy that cell and paste it below before starting this part. 

In [20]:
import random
import pandas as pd

# Define the range for longitude and latitude
lon_range = (-105, -100)
lat_range = (50, 52)

# Define the list of soil types
soil_types = ['black', 'gray', 'dark brown', 'brown', None]

# Create an empty list to store the farms
farms = []

# Generate 40 farms
for i in range(200):
    farm = {
        'farm_name': f'Farm {i+1}', # f is formated string
        'farm_lon': round(random.uniform(lon_range[0], lon_range[1]), 2), # random lon with 2 decimal points
        'farm_lat': round(random.uniform(lat_range[0], lat_range[1]), 2), # rantom lat with 2 decimal points
        'temperature': round(random.uniform(18, 33), 1), #random temp with 1 decimal points
        'precipitation': round(random.uniform(20, 90), 1), # random prec with 1 decimal points
        'soil_type': random.choice(soil_types) # random soil types from above list
    }
    farms.append(farm)

In [21]:
df = # your code here

SyntaxError: invalid syntax (4060184953.py, line 1)

1. Select the rows where the temperature is above 20 degrees Celsius.

In [22]:
## Your code here down


## Your code here up

2. Sort the DataFrame by precipitation in descending order.

In [23]:
## Your code here down


## Your code here up

3. Filter the DataFrame to include only the farms located within latitude (51.15 & 51.00) range.

In [24]:
## Your code here down


## Your code here up

 4. Calculate the standard deviation of precipitation for each soil type.

In [25]:
## Your code here down


## Your code here up

5. Calculate the cumulative sum of precipitation for each soil type.

In [26]:
## Your code here down


## Your code here up

6. Determine the top 3 farms with the highest average temperature.

In [27]:
## Your code here down


## Your code here up

7. Find famrs in each soil type that have the highest temperature.

In [28]:
## Your code here down


## Your code here up

8. Create new column 'percentage_tot_prec' and add the percentage contribution of each farm's precipitation (relative to total precipitation) to the column.

In [29]:
## Your code here down


## Your code here up

9. Create a new column called "precipitation_rank" that ranks the farms based on their precipitation in ascending order, with ties being assigned the same rank.

In [ ]:
## Your code here down


## Your code here up

10. Normalize the temperature column to a range between 0 and 1 for each farm.

In [ ]:
## Your code here down


## Your code here up

# Assignment 4

## ETL

11. Change column types accordingly.

In [ ]:
## Your code here down


## Your code here up

## EDA

12. Find missing values and give information how would you handle them

In [ ]:
## Your code here down


## Your code here up

13. Find outliers if there is any how would you handle them

In [ ]:
## Your code here down


## Your code here up

14. Find descriptive statistics for relavant columns and plot them by using bars.

In [ ]:
## Your code here down


## Your code here up

15. Plot the distribution of relevant columns.

In [ ]:
## Your code here down


## Your code here up